/* Just a list of keycodes for type.js */

const keycodes = {
    // "keyName": [keyCode, "humanName", needsShift, enabled],
    "a": [0, "a", false, true],
    "b": [11, "b", false, true],
    "c": [8, "c", false, true],
    "d": [2, "d", false, true],
    "e": [14, "e", false, true],
    "f": [3, "f", false, true],
    "g": [5, "g", false, true],
    "h": [4, "h", false, true],
    "i": [34, "i", false, true],
    "j": [38, "j", false, true],
    "k": [40, "k", false, true],
    "l": [37, "l", false, true],
    "m": [46, "m", false, true],
    "n": [45, "n", false, true],
    "o": [31, "o", false, true],
    "p": [35, "p", false, true],
    "q": [12, "q", false, true],
    "r": [15, "r", false, true],
    "s": [1, "s", false, true],
    "t": [17, "t", false, true],
    "u": [32, "u", false, true],
    "v": [9, "v", false, true],
    "w": [13, "w", false, true],
    "x": [7, "x", false, true],
    "y": [16, "y", false, true],
    "z": [6, "z", false, true],

    "A": [0, "A", true, true],
    "B": [11, "B", true, true],
    "C": [8, "C", true, true],
    "D": [2, "D", true, true],
    "E": [14, "E", true, true],
    "F": [3, "F", true, true],
    "G": [5, "G", true, true],
    "H": [4, "H", true, true],
    "I": [34, "I", true, true],
    "J": [38, "J", true, true],
    "K": [40, "K", true, true],
    "L": [37, "L", true, true],
    "M": [46, "M", true, true],
    "N": [45, "N", true, true],
    "O": [31, "O", true, true],
    "P": [35, "P", true, true],
    "Q": [12, "Q", true, true],
    "R": [15, "R", true, true],
    "S": [1, "S", true, true],
    "T": [17, "T", true, true],
    "U": [32, "U", true, true],
    "V": [9, "V", true, true],
    "W": [13, "W", true, true],
    "X": [7, "X", true, true],
    "Y": [16, "Y", true, true],
    "Z": [6, "Z", true, true],

    "0": [29, "0", false, true],
    "1": [18, "1", false, true],
    "2": [19, "2", false, true],
    "3": [20, "3", false, true],
    "4": [21, "4", false, true],
    "5": [23, "5", false, true],
    "6": [22, "6", false, true],
    "7": [26, "7", false, true],
    "8": [28, "8", false, true],
    "9": [25, "9", false, true],

    "!": [18, "!", true, true],
    "@": [19, "@", true, true],
    "#": [20, "#", true, true],
    "$": [21, "$", true, true],
    "%": [23, "%", true, true],
    "^": [22, "^", true, true],
    "&": [26, "&", true, true],
    "*": [28, "*", true, true],
    "(": [25, "(", true, true],
    ")": [29, ")", true, true],

    "-": [27, "-", false, true],
    "_": [27, "_", true, true],
    "=": [24, "=", false, true],
    "+": [24, "+", true, true],

    "[": [33, "[", false, true],
    "{": [33, "{", true, true],
    "]": [30, "]", false, true],
    "}": [30, "}", true, true],

    "\\": [42, "\\", false, true],
    "|": [42, "|", true, true],

    ";": [41, ";", false, true],
    ":": [41, ";", true, true],

    "'": [39, "'", false, true],
    "\"": [39, "\"", true, true],

    ",": [43, ",", false, true],
    "<": [43, "<,>", true, true],

    ".": [47, ".", false, true],
    ">": [47, ">", true, true],

    "/": [44, "/", false, true],
    "?": [44, "?", true, true],

    "`": [50, "`", false, true],
    "~": [50, "~", true, true],

    " ": [49, "space", false, true],
    "Enter": [36, "return", false, true],
    "Escape": [53, "esc", false, true],

    "ArrowLeft": [123, "left arrow", false, true],
    "ArrowRight": [124, "right arrow", false, true],
    "ArrowDown": [125, "down arrow", false, true],
    "ArrowUp": [126, "up arrow", false, true]
}

module.exports = keycodes;